export const Colors = {
  primary: "#00458f",
  primaryContainer: "#005cbb",
  primaryFixed: "#d7e2ff",
  onPrimary: "#ffffff",
  onPrimaryFixed: "#001b3f",
  onPrimaryFixedVariant: "#00458f",
  onPrimaryContainer: "#c7d9ff",
  secondary: "#006a6a",
  secondaryContainer: "#9deeed",
  onSecondary: "#ffffff",
  onSecondaryContainer: "#0b6e6e",
  tertiary: "#004e58",
  tertiaryContainer: "#006874",
  onTertiaryContainer: "#97e4f2",
  error: "#ba1a1a",
  errorContainer: "#ffdad6",
  onErrorContainer: "#93000a",
  surface: "#f9f9ff",
  surfaceContainerLow: "#f2f3fc",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerHighest: "#e1e2ea",
  surfaceContainer: "#ecedf6",
  onSurface: "#191c22",
  onSurfaceVariant: "#424752",
  outline: "#727784",
  outlineVariant: "#c2c6d4",
};

export const Shadows = {
  editorial: {
    shadowColor: "#191c22",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 30,
    elevation: 4,
  },
  small: {
    shadowColor: "#191c22",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
};
